#ifndef SHAREDRANDOMIZERWINDOW_H
#define SHAREDRANDOMIZERWINDOW_H

#include <QWidget>
#include <QMap>
#include <QVariant>
#include <QMessageBox>
#include <QStackedWidget>
#include <QPushButton>
#include <QVBoxLayout>
#include <QLabel>
#include <QComboBox>
#include <QCheckBox>
#include <QSpinBox>
#include <QJsonObject>
#include <QJsonDocument>
#include <QJsonArray>
#include <QGroupBox>
#include <QStringListModel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QTabBar>
#include <QLineEdit>
#include <QScrollArea>
#include <QFormLayout>
#include <QCompleter>
#include <QFileDialog>
#include <nlohmann/json.hpp>
#include "../sv_randomizer_headers/sv_shared_class.h"

class SharedRandomizerWindow: public SVShared{
protected:
    // Variables - uninitialized
    QMap<QString, QVariant> settings;
    QStringList starterNames;
    QMessageBox* progressBar = nullptr;

    // Protected Functions
    // virtual int obtainPokemonGenderRatios(QString pokemonStatsFilePath);
    // virtual QMap<QString, QVariant> setUpSettings(QMap<QString, QVariant> s);
    virtual QScrollArea* setupStartersWidget() = 0;
    virtual QScrollArea* setupPersonalWidget() = 0;
    virtual QScrollArea* setupWildWidget() = 0;
    virtual QScrollArea* setupTrainersWidget() = 0;
    virtual QScrollArea* setupBossWidget() = 0;
    // virtual QScrollArea* setupShopWidget();
    virtual void initializeSettings() =0;
    virtual void setupAllowedPokemon(QVBoxLayout *outerBox, allowedPokemonLimiter& details)=0;
    virtual void runRandomizer() = 0;

public:
    // Functions - Not Overloaded
    // virtual bool checkAndDeleteFiles(QString fileToCheck);
    // virtual void createFolderHierarchy(const QString& folder);
    // virtual QString getItemForPokemon(int pokemon, int form);
    // virtual QString getPokemonItemId(int index, int form);
    // virtual int getPokemonItemValue(int index, int form);

    // Functions Overloaded
    // virtual QList<int> getDevIdsOfAllowedPokemon(allowedPokemonLimiter limiterCheck);
    // virtual QList<int> getDevIdsOfAllowedPokemon(allowedPokemonLimiter limiterCheck, QList<int> &allowedLegends);

//     // TODO
    virtual QJsonDocument exportSettings(QMap<QString, QVariant> map) =0;
//     // void runRandomizer();
//     // void switchTabs(QStackedWidget* sw, int i =0);
//     // void sendMessageOfConfirmation(QString message);

    virtual void importSettings() =0;

    QMap<QString, QStringList> nationalDexPokemonNamesAndForms = {
        {"Bulbasaur", {"—"}},
        {"Ivysaur", {"—"}},
        {"Venusaur", {"—"}},
        {"Charmander", {"—"}},
        {"Charmeleon", {"—"}},
        {"Charizard", {"—"}},
        {"Squirtle", {"—"}},
        {"Wartortle", {"—"}},
        {"Blastoise", {"—"}},
        {"Ekans", {"—"}},
        {"Arbok", {"—"}},
        {"Pikachu", {"Normal","Original","Hoenn","Sinnoh","Unova","Kalos","Alola","Partner","World"}},
        {"Raichu", {"Normal","Alolan"}},
        {"Sandshrew", {"Normal","Alolan"}},
        {"Sandslash", {"Normal","Alolan"}},
        {"Clefairy", {"—"}},
        {"Clefable", {"—"}},
        {"Vulpix", {"Normal","Alolan"}},
        {"Ninetales", {"Normal","Alolan"}},
        {"Jigglypuff", {"—"}},
        {"Wigglytuff", {"—"}},
        {"Oddish", {"—"}},
        {"Gloom", {"—"}},
        {"Vileplume", {"—"}},
        {"Venonat", {"—"}},
        {"Venomoth", {"—"}},
        {"Diglett", {"Normal","Alolan"}},
        {"Dugtrio", {"Normal","Alolan"}},
        {"Meowth", {"Normal","Alolan","Galarian"}},
        {"Persian", {"Normal","Alolan"}},
        {"Psyduck", {"—"}},
        {"Golduck", {"—"}},
        {"Mankey", {"—"}},
        {"Primeape", {"—"}},
        {"Growlithe", {"Normal","Hisuian"}},
        {"Arcanine", {"Normal","Hisuian"}},
        {"Poliwag", {"—"}},
        {"Poliwhirl", {"—"}},
        {"Poliwrath", {"—"}},
        {"Bellsprout", {"—"}},
        {"Weepinbell", {"—"}},
        {"Victreebel", {"—"}},
        {"Tentacool", {"—"}},
        {"Tentacruel", {"—"}},
        {"Geodude", {"Normal","Alolan"}},
        {"Graveler", {"Normal","Alolan"}},
        {"Golem", {"Normal","Alolan"}},
        {"Slowpoke", {"Normal","Galarian"}},
        {"Slowbro", {"Normal","Galarian"}},
        {"Magnemite", {"—"}},
        {"Magneton", {"—"}},
        {"Doduo", {"—"}},
        {"Dodrio", {"—"}},
        {"Seel", {"—"}},
        {"Dewgong", {"—"}},
        {"Grimer", {"Normal","Alolan"}},
        {"Muk", {"Normal","Alolan"}},
        {"Shellder", {"—"}},
        {"Cloyster", {"—"}},
        {"Gastly", {"—"}},
        {"Haunter", {"—"}},
        {"Gengar", {"—"}},
        {"Drowzee", {"—"}},
        {"Hypno", {"—"}},
        {"Voltorb", {"Normal","Hisuian"}},
        {"Electrode", {"Normal","Hisuian"}},
        {"Exeggcute", {"—"}},
        {"Exeggutor", {"Normal","Alolan"}},
        {"Hitmonlee", {"—"}},
        {"Hitmonchan", {"—"}},
        {"Koffing", {"—"}},
        {"Weezing", {"Normal","Galarian"}},
        {"Rhyhorn", {"—"}},
        {"Rhydon", {"—"}},
        {"Chansey", {"—"}},
        {"Horsea", {"—"}},
        {"Seadra", {"—"}},
        {"Scyther", {"—"}},
        {"Electabuzz", {"—"}},
        {"Magmar", {"—"}},
        {"Tauros", {"Normal","Paldean (Combat)","Paldean (Blaze)","Paldean (Aqua)"}},
        {"Magikarp", {"—"}},
        {"Gyarados", {"—"}},
        {"Lapras", {"—"}},
        {"Ditto", {"—"}},
        {"Eevee", {"—"}},
        {"Vaporeon", {"—"}},
        {"Jolteon", {"—"}},
        {"Flareon", {"—"}},
        {"Porygon", {"—"}},
        {"Snorlax", {"—"}},
        {"Articuno", {"Normal","Galarian"}},
        {"Zapdos", {"Normal","Galarian"}},
        {"Moltres", {"Normal","Galarian"}},
        {"Dratini", {"—"}},
        {"Dragonair", {"—"}},
        {"Dragonite", {"—"}},
        {"Mewtwo", {"—"}},
        {"Mew", {"—"}},
        {"Chikorita", {"—"}},
        {"Bayleef", {"—"}},
        {"Meganium", {"—"}},
        {"Cyndaquil", {"—"}},
        {"Quilava", {"—"}},
        {"Typhlosion", {"Normal","Hisuian"}},
        {"Totodile", {"—"}},
        {"Croconaw", {"—"}},
        {"Feraligatr", {"—"}},
        {"Sentret", {"—"}},
        {"Furret", {"—"}},
        {"Hoothoot", {"—"}},
        {"Noctowl", {"—"}},
        {"Spinarak", {"—"}},
        {"Ariados", {"—"}},
        {"Chinchou", {"—"}},
        {"Lanturn", {"—"}},
        {"Pichu", {"—"}},
        {"Cleffa", {"—"}},
        {"Igglybuff", {"—"}},
        {"Mareep", {"—"}},
        {"Flaaffy", {"—"}},
        {"Ampharos", {"—"}},
        {"Bellossom", {"—"}},
        {"Marill", {"—"}},
        {"Azumarill", {"—"}},
        {"Sudowoodo", {"—"}},
        {"Politoed", {"—"}},
        {"Hoppip", {"—"}},
        {"Skiploom", {"—"}},
        {"Jumpluff", {"—"}},
        {"Aipom", {"—"}},
        {"Sunkern", {"—"}},
        {"Sunflora", {"—"}},
        {"Yanma", {"—"}},
        {"Wooper", {"Normal","Paldean"}},
        {"Quagsire", {"—"}},
        {"Espeon", {"—"}},
        {"Umbreon", {"—"}},
        {"Murkrow", {"—"}},
        {"Slowking", {"Normal","Galarian"}},
        {"Misdreavus", {"—"}},
        {"Girafarig", {"—"}},
        {"Pineco", {"—"}},
        {"Forretress", {"—"}},
        {"Dunsparce", {"—"}},
        {"Gligar", {"—"}},
        {"Snubbull", {"—"}},
        {"Granbull", {"—"}},
        {"Qwilfish", {"Normal","Hisuian"}},
        {"Scizor", {"—"}},
        {"Heracross", {"—"}},
        {"Sneasel", {"Normal","Hisuian"}},
        {"Teddiursa", {"—"}},
        {"Ursaring", {"—"}},
        {"Slugma", {"—"}},
        {"Magcargo", {"—"}},
        {"Swinub", {"—"}},
        {"Piloswine", {"—"}},
        {"Delibird", {"—"}},
        {"Skarmory", {"—"}},
        {"Houndour", {"—"}},
        {"Houndoom", {"—"}},
        {"Kingdra", {"—"}},
        {"Phanpy", {"—"}},
        {"Donphan", {"—"}},
        {"Porygon2", {"—"}},
        {"Stantler", {"—"}},
        {"Smeargle", {"—"}},
        {"Tyrogue", {"—"}},
        {"Hitmontop", {"—"}},
        {"Elekid", {"—"}},
        {"Magby", {"—"}},
        {"Blissey", {"—"}},
        {"Raikou", {"—"}},
        {"Entei", {"—"}},
        {"Suicune", {"—"}},
        {"Larvitar", {"—"}},
        {"Pupitar", {"—"}},
        {"Tyranitar", {"—"}},
        {"Lugia", {"—"}},
        {"Ho-Oh", {"—"}},
        {"Treecko", {"—"}},
        {"Grovyle", {"—"}},
        {"Sceptile", {"—"}},
        {"Torchic", {"—"}},
        {"Combusken", {"—"}},
        {"Blaziken", {"—"}},
        {"Mudkip", {"—"}},
        {"Marshtomp", {"—"}},
        {"Swampert", {"—"}},
        {"Poochyena", {"—"}},
        {"Mightyena", {"—"}},
        {"Lotad", {"—"}},
        {"Lombre", {"—"}},
        {"Ludicolo", {"—"}},
        {"Seedot", {"—"}},
        {"Nuzleaf", {"—"}},
        {"Shiftry", {"—"}},
        {"Wingull", {"—"}},
        {"Pelipper", {"—"}},
        {"Ralts", {"—"}},
        {"Kirlia", {"—"}},
        {"Gardevoir", {"—"}},
        {"Surskit", {"—"}},
        {"Masquerain", {"—"}},
        {"Shroomish", {"—"}},
        {"Breloom", {"—"}},
        {"Slakoth", {"—"}},
        {"Vigoroth", {"—"}},
        {"Slaking", {"—"}},
        {"Makuhita", {"—"}},
        {"Hariyama", {"—"}},
        {"Azurill", {"—"}},
        {"Nosepass", {"—"}},
        {"Sableye", {"—"}},
        {"Meditite", {"—"}},
        {"Medicham", {"—"}},
        {"Plusle", {"—"}},
        {"Minun", {"—"}},
        {"Volbeat", {"—"}},
        {"Illumise", {"—"}},
        {"Gulpin", {"—"}},
        {"Swalot", {"—"}},
        {"Numel", {"—"}},
        {"Camerupt", {"—"}},
        {"Torkoal", {"—"}},
        {"Spoink", {"—"}},
        {"Grumpig", {"—"}},
        {"Trapinch", {"—"}},
        {"Vibrava", {"—"}},
        {"Flygon", {"—"}},
        {"Cacnea", {"—"}},
        {"Cacturne", {"—"}},
        {"Swablu", {"—"}},
        {"Altaria", {"—"}},
        {"Zangoose", {"—"}},
        {"Seviper", {"—"}},
        {"Barboach", {"—"}},
        {"Whiscash", {"—"}},
        {"Corphish", {"—"}},
        {"Crawdaunt", {"—"}},
        {"Feebas", {"—"}},
        {"Milotic", {"—"}},
        {"Shuppet", {"—"}},
        {"Banette", {"—"}},
        {"Duskull", {"—"}},
        {"Dusclops", {"—"}},
        {"Tropius", {"—"}},
        {"Chimecho", {"—"}},
        {"Snorunt", {"—"}},
        {"Glalie", {"—"}},
        {"Luvdisc", {"—"}},
        {"Bagon", {"—"}},
        {"Shelgon", {"—"}},
        {"Salamence", {"—"}},
        {"Beldum", {"—"}},
        {"Metang", {"—"}},
        {"Metagross", {"—"}},
        {"Regirock", {"—"}},
        {"Regice", {"—"}},
        {"Registeel", {"—"}},
        {"Latias", {"—"}},
        {"Latios", {"—"}},
        {"Kyogre", {"—"}},
        {"Groudon", {"—"}},
        {"Rayquaza", {"—"}},
        {"Jirachi", {"—"}},
        {"Deoxys", {"Normal","Attack","Defense","Speed"}},
        {"Turtwig", {"—"}},
        {"Grotle", {"—"}},
        {"Torterra", {"—"}},
        {"Chimchar", {"—"}},
        {"Monferno", {"—"}},
        {"Infernape", {"—"}},
        {"Piplup", {"—"}},
        {"Prinplup", {"—"}},
        {"Empoleon", {"—"}},
        {"Starly", {"—"}},
        {"Staravia", {"—"}},
        {"Staraptor", {"—"}},
        {"Kricketot", {"—"}},
        {"Kricketune", {"—"}},
        {"Shinx", {"—"}},
        {"Luxio", {"—"}},
        {"Luxray", {"—"}},
        {"Cranidos", {"—"}},
        {"Rampardos", {"—"}},
        {"Shieldon", {"—"}},
        {"Bastiodon", {"—"}},
        {"Combee", {"—"}},
        {"Vespiquen", {"—"}},
        {"Pachirisu", {"—"}},
        {"Buizel", {"—"}},
        {"Floatzel", {"—"}},
        {"Shellos", {"West","East"}},
        {"Gastrodon", {"West","East"}},
        {"Ambipom", {"—"}},
        {"Drifloon", {"—"}},
        {"Drifblim", {"—"}},
        {"Mismagius", {"—"}},
        {"Honchkrow", {"—"}},
        {"Chingling", {"—"}},
        {"Stunky", {"—"}},
        {"Skuntank", {"—"}},
        {"Bronzor", {"—"}},
        {"Bronzong", {"—"}},
        {"Bonsly", {"—"}},
        {"Happiny", {"—"}},
        {"Spiritomb", {"—"}},
        {"Gible", {"—"}},
        {"Gabite", {"—"}},
        {"Garchomp", {"—"}},
        {"Munchlax", {"—"}},
        {"Riolu", {"—"}},
        {"Lucario", {"—"}},
        {"Hippopotas", {"—"}},
        {"Hippowdon", {"—"}},
        {"Croagunk", {"—"}},
        {"Toxicroak", {"—"}},
        {"Finneon", {"—"}},
        {"Lumineon", {"—"}},
        {"Snover", {"—"}},
        {"Abomasnow", {"—"}},
        {"Weavile", {"—"}},
        {"Magnezone", {"—"}},
        {"Rhyperior", {"—"}},
        {"Electivire", {"—"}},
        {"Magmortar", {"—"}},
        {"Yanmega", {"—"}},
        {"Leafeon", {"—"}},
        {"Glaceon", {"—"}},
        {"Gliscor", {"—"}},
        {"Mamoswine", {"—"}},
        {"Porygon-Z", {"—"}},
        {"Gallade", {"—"}},
        {"Probopass", {"—"}},
        {"Dusknoir", {"—"}},
        {"Froslass", {"—"}},
        {"Rotom", {"Normal","Heat","Wash","Frost","Fan","Mow"}},
        {"Uxie", {"—"}},
        {"Mesprit", {"—"}},
        {"Azelf", {"—"}},
        {"Dialga", {"Normal","Origin"}},
        {"Palkia", {"Normal","Origin"}},
        {"Heatran", {"—"}},
        {"Regigigas", {"—"}},
        {"Giratina", {"Altered","Origin"}},
        {"Cresselia", {"—"}},
        {"Phione", {"—"}},
        {"Manaphy", {"—"}},
        {"Darkrai", {"—"}},
        {"Shaymin", {"Land","Sky"}},
        {"Arceus", {"Normal","Fighting","Flying","Poison","Ground","Rock","Bug","Ghost","Steel","Fire","Water","Grass","Electric","Psychic","Ice","Dragon","Dark","Fairy"}},
        {"Snivy", {"—"}},
        {"Servine", {"—"}},
        {"Serperior", {"—"}},
        {"Tepig", {"—"}},
        {"Pignite", {"—"}},
        {"Emboar", {"—"}},
        {"Oshawott", {"—"}},
        {"Dewott", {"—"}},
        {"Samurott", {"Normal","Hisuian"}},
        {"Blitzle", {"—"}},
        {"Zebstrika", {"—"}},
        {"Drilbur", {"—"}},
        {"Excadrill", {"—"}},
        {"Timburr", {"—"}},
        {"Gurdurr", {"—"}},
        {"Conkeldurr", {"—"}},
        {"Sewaddle", {"—"}},
        {"Swadloon", {"—"}},
        {"Leavanny", {"—"}},
        {"Cottonee", {"—"}},
        {"Whimsicott", {"—"}},
        {"Petilil", {"—"}},
        {"Lilligant", {"Normal","Hisuian"}},
        {"Basculin", {"Red","Blue","White"}},
        {"Sandile", {"—"}},
        {"Krokorok", {"—"}},
        {"Krookodile", {"—"}},
        {"Scraggy", {"—"}},
        {"Scrafty", {"—"}},
        {"Zorua", {"Normal","Hisuian"}},
        {"Zoroark", {"Normal","Hisuian"}},
        {"Minccino", {"—"}},
        {"Cinccino", {"—"}},
        {"Gothita", {"—"}},
        {"Gothorita", {"—"}},
        {"Gothitelle", {"—"}},
        {"Solosis", {"—"}},
        {"Duosion", {"—"}},
        {"Reuniclus", {"—"}},
        {"Ducklett", {"—"}},
        {"Swanna", {"—"}},
        {"Deerling", {"Spring","Summer","Autumn","Winter"}},
        {"Sawsbuck", {"Spring","Summer","Autumn","Winter"}},
        {"Foongus", {"—"}},
        {"Amoonguss", {"—"}},
        {"Alomomola", {"—"}},
        {"Joltik", {"—"}},
        {"Galvantula", {"—"}},
        {"Tynamo", {"—"}},
        {"Eelektrik", {"—"}},
        {"Eelektross", {"—"}},
        {"Litwick", {"—"}},
        {"Lampent", {"—"}},
        {"Chandelure", {"—"}},
        {"Axew", {"—"}},
        {"Fraxure", {"—"}},
        {"Haxorus", {"—"}},
        {"Cubchoo", {"—"}},
        {"Beartic", {"—"}},
        {"Cryogonal", {"—"}},
        {"Mienfoo", {"—"}},
        {"Mienshao", {"—"}},
        {"Golett", {"—"}},
        {"Golurk", {"—"}},
        {"Pawniard", {"—"}},
        {"Bisharp", {"—"}},
        {"Rufflet", {"—"}},
        {"Braviary", {"Normal","Hisuian"}},
        {"Vullaby", {"—"}},
        {"Mandibuzz", {"—"}},
        {"Deino", {"—"}},
        {"Zweilous", {"—"}},
        {"Hydreigon", {"—"}},
        {"Larvesta", {"—"}},
        {"Volcarona", {"—"}},
        {"Cobalion", {"—"}},
        {"Terrakion", {"—"}},
        {"Virizion", {"—"}},
        {"Tornadus", {"Incarnate","Therian"}},
        {"Thundurus", {"Incarnate","Therian"}},
        {"Reshiram", {"—"}},
        {"Zekrom", {"—"}},
        {"Landorus", {"Incarnate","Therian"}},
        {"Kyurem", {"Normal","White","Black"}},
        {"Keldeo", {"Ordinary","Resolute"}},
        {"Meloetta", {"Aria","Pirouette"}},
        {"Chespin", {"—"}},
        {"Quilladin", {"—"}},
        {"Chesnaught", {"—"}},
        {"Fennekin", {"—"}},
        {"Braixen", {"—"}},
        {"Delphox", {"—"}},
        {"Froakie", {"—"}},
        {"Frogadier", {"—"}},
        {"Greninja", {"Normal","Battle Bond"}},
        {"Fletchling", {"—"}},
        {"Fletchinder", {"—"}},
        {"Talonflame", {"—"}},
        {"Scatterbug", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Spewpa", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Vivillon", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Litleo", {"—"}},
        {"Pyroar", {"—"}},
        {"Flabébé", {"Red","Yellow","Orange","Blue","White"}},
        {"Floette", {"Red","Yellow","Orange","Blue","White","Eternal"}},
        {"Florges", {"Red","Yellow","Orange","Blue","White"}},
        {"Skiddo", {"—"}},
        {"Gogoat", {"—"}},
        {"Espurr", {"—"}},
        {"Meowstic", {"Male","Female"}},
        {"Inkay", {"—"}},
        {"Malamar", {"—"}},
        {"Skrelp", {"—"}},
        {"Dragalge", {"—"}},
        {"Clauncher", {"—"}},
        {"Clawitzer", {"—"}},
        {"Sylveon", {"—"}},
        {"Hawlucha", {"—"}},
        {"Dedenne", {"—"}},
        {"Carbink", {"—"}},
        {"Goomy", {"—"}},
        {"Sliggoo", {"Normal","Hisuian"}},
        {"Goodra", {"Normal","Hisuian"}},
        {"Klefki", {"—"}},
        {"Phantump", {"—"}},
        {"Trevenant", {"—"}},
        {"Bergmite", {"—"}},
        {"Avalugg", {"Normal","Hisuian"}},
        {"Noibat", {"—"}},
        {"Noivern", {"—"}},
        {"Diancie", {"—"}},
        {"Hoopa", {"Confined","Unbound"}},
        {"Volcanion", {"—"}},
        {"Rowlet", {"—"}},
        {"Dartrix", {"—"}},
        {"Decidueye", {"Normal","Hisuian"}},
        {"Litten", {"—"}},
        {"Torracat", {"—"}},
        {"Incineroar", {"—"}},
        {"Popplio", {"—"}},
        {"Brionne", {"—"}},
        {"Primarina", {"—"}},
        {"Pikipek", {"—"}},
        {"Trumbeak", {"—"}},
        {"Toucannon", {"—"}},
        {"Yungoos", {"—"}},
        {"Gumshoos", {"—"}},
        {"Grubbin", {"—"}},
        {"Charjabug", {"—"}},
        {"Vikavolt", {"—"}},
        {"Crabrawler", {"—"}},
        {"Crabominable", {"—"}},
        {"Oricorio", {"Baile","Pom-Pom","Pa’u","Sensu"}},
        {"Cutiefly", {"—"}},
        {"Ribombee", {"—"}},
        {"Rockruff", {"Normal","Own Tempo"}},
        {"Lycanroc", {"Midday","Midnight","Dusk"}},
        {"Mareanie", {"—"}},
        {"Toxapex", {"—"}},
        {"Mudbray", {"—"}},
        {"Mudsdale", {"—"}},
        {"Dewpider", {"—"}},
        {"Araquanid", {"—"}},
        {"Fomantis", {"—"}},
        {"Lurantis", {"—"}},
        {"Salandit", {"—"}},
        {"Salazzle", {"—"}},
        {"Bounsweet", {"—"}},
        {"Steenee", {"—"}},
        {"Tsareena", {"—"}},
        {"Comfey", {"—"}},
        {"Oranguru", {"—"}},
        {"Passimian", {"—"}},
        {"Sandygast", {"—"}},
        {"Palossand", {"—"}},
        {"Minior", {"M-Red","M-Orange","M-Yellow","M-Green","M-Blue","M-Indigo","M-Violet","C-Red","C-Orange","C-Yellow","C-Green","C-Blue","C-Indigo","C-Violet"}},
        {"Komala", {"—"}},
        {"Mimikyu", {"Disguised","Busted"}},
        {"Bruxish", {"—"}},
        {"Jangmo-o", {"—"}},
        {"Hakamo-o", {"—"}},
        {"Kommo-o", {"—"}},
        {"Cosmog", {"—"}},
        {"Cosmoem", {"—"}},
        {"Solgaleo", {"—"}},
        {"Lunala", {"—"}},
        {"Necrozma", {"Normal","Dusk Mane","Dawn Wings"}},
        {"Magearna", {"Normal","Original"}},
        {"Grookey", {"—"}},
        {"Thwackey", {"—"}},
        {"Rillaboom", {"—"}},
        {"Scorbunny", {"—"}},
        {"Raboot", {"—"}},
        {"Cinderace", {"—"}},
        {"Sobble", {"—"}},
        {"Drizzile", {"—"}},
        {"Inteleon", {"—"}},
        {"Skwovet", {"—"}},
        {"Greedent", {"—"}},
        {"Rookidee", {"—"}},
        {"Corvisquire", {"—"}},
        {"Corviknight", {"—"}},
        {"Chewtle", {"—"}},
        {"Drednaw", {"—"}},
        {"Rolycoly", {"—"}},
        {"Carkol", {"—"}},
        {"Coalossal", {"—"}},
        {"Applin", {"—"}},
        {"Flapple", {"—"}},
        {"Appletun", {"—"}},
        {"Silicobra", {"—"}},
        {"Sandaconda", {"—"}},
        {"Cramorant", {"Normal","Gulping","Gorging"}},
        {"Arrokuda", {"—"}},
        {"Barraskewda", {"—"}},
        {"Toxel", {"—"}},
        {"Toxtricity", {"Amped","Low Key"}},
        {"Sinistea", {"Phony","Antique"}},
        {"Polteageist", {"Phony","Antique"}},
        {"Hatenna", {"—"}},
        {"Hattrem", {"—"}},
        {"Hatterene", {"—"}},
        {"Impidimp", {"—"}},
        {"Morgrem", {"—"}},
        {"Grimmsnarl", {"—"}},
        {"Perrserker", {"—"}},
        {"Milcery", {"—"}},
        {"Alcremie", {"Vanilla Cream","Ruby Cream","Matcha Cream","Mint Cream","Lemon Cream","Salted Cream","Ruby Swirl","Caramel Swirl","Rainbow Swirl"}},
        {"Falinks", {"—"}},
        {"Pincurchin", {"—"}},
        {"Snom", {"—"}},
        {"Frosmoth", {"—"}},
        {"Stonjourner", {"—"}},
        {"Eiscue", {"Ice Face","Noice Face"}},
        {"Indeedee", {"Male","Female"}},
        {"Morpeko", {"Full Belly","Hangry"}},
        {"Cufant", {"—"}},
        {"Copperajah", {"—"}},
        {"Duraludon", {"—"}},
        {"Dreepy", {"—"}},
        {"Drakloak", {"—"}},
        {"Dragapult", {"—"}},
        {"Zacian", {"Hero","Crowned"}},
        {"Zamazenta", {"Hero","Crowned"}},
        {"Eternatus", {"—"}},
        {"Kubfu", {"—"}},
        {"Urshifu", {"Single","Rapid"}},
        {"Zarude", {"Normal","Dada"}},
        {"Regieleki", {"—"}},
        {"Regidrago", {"—"}},
        {"Glastrier", {"—"}},
        {"Spectrier", {"—"}},
        {"Calyrex", {"Normal","Ice","Shadow"}},
        {"Wyrdeer", {"—"}},
        {"Kleavor", {"—"}},
        {"Ursaluna", {"Normal","Bloodmoon"}},
        {"Basculegion", {"Male","Female"}},
        {"Sneasler", {"—"}},
        {"Overqwil", {"—"}},
        {"Enamorus", {"Incarnate","Therian"}},
        {"Sprigatito", {"—"}},
        {"Floragato", {"—"}},
        {"Meowscarada", {"—"}},
        {"Fuecoco", {"—"}},
        {"Crocalor", {"—"}},
        {"Skeledirge", {"—"}},
        {"Quaxly", {"—"}},
        {"Quaxwell", {"—"}},
        {"Quaquaval", {"—"}},
        {"Lechonk", {"—"}},
        {"Oinkologne", {"Male","Female"}},
        {"Tarountula", {"—"}},
        {"Spidops", {"—"}},
        {"Nymble", {"—"}},
        {"Lokix", {"—"}},
        {"Pawmi", {"—"}},
        {"Pawmo", {"—"}},
        {"Pawmot", {"—"}},
        {"Tandemaus", {"—"}},
        {"Maushold", {"Three","Four"}},
        {"Fidough", {"—"}},
        {"Dachsbun", {"—"}},
        {"Smoliv", {"—"}},
        {"Dolliv", {"—"}},
        {"Arboliva", {"—"}},
        {"Squawkabilly", {"Green","Blue","Yellow","White"}},
        {"Nacli", {"—"}},
        {"Naclstack", {"—"}},
        {"Garganacl", {"—"}},
        {"Charcadet", {"—"}},
        {"Armarouge", {"—"}},
        {"Ceruledge", {"—"}},
        {"Tadbulb", {"—"}},
        {"Bellibolt", {"—"}},
        {"Wattrel", {"—"}},
        {"Kilowattrel", {"—"}},
        {"Maschiff", {"—"}},
        {"Mabosstiff", {"—"}},
        {"Shroodle", {"—"}},
        {"Grafaiai", {"—"}},
        {"Bramblin", {"—"}},
        {"Brambleghast", {"—"}},
        {"Toedscool", {"—"}},
        {"Toedscruel", {"—"}},
        {"Klawf", {"—"}},
        {"Capsakid", {"—"}},
        {"Scovillain", {"—"}},
        {"Rellor", {"—"}},
        {"Rabsca", {"—"}},
        {"Flittle", {"—"}},
        {"Espathra", {"—"}},
        {"Tinkatink", {"—"}},
        {"Tinkatuff", {"—"}},
        {"Tinkaton", {"—"}},
        {"Wiglett", {"—"}},
        {"Wugtrio", {"—"}},
        {"Bombirdier", {"—"}},
        {"Finizen", {"—"}},
        {"Palafin", {"Zero","Hero"}},
        {"Varoom", {"—"}},
        {"Revavroom", {"—"}},
        {"Cyclizar", {"—"}},
        {"Orthworm", {"—"}},
        {"Glimmet", {"—"}},
        {"Glimmora", {"—"}},
        {"Greavard", {"—"}},
        {"Houndstone", {"—"}},
        {"Flamigo", {"—"}},
        {"Cetoddle", {"—"}},
        {"Cetitan", {"—"}},
        {"Veluza", {"—"}},
        {"Dondozo", {"—"}},
        {"Tatsugiri", {"Curly","Droopy","Stretchy"}},
        {"Annihilape", {"—"}},
        {"Clodsire", {"—"}},
        {"Farigiraf", {"—"}},
        {"Dudunsparce", {"Two","Three"}},
        {"Kingambit", {"—"}},
        {"Great Tusk", {"—"}},
        {"Scream Tail", {"—"}},
        {"Brute Bonnet", {"—"}},
        {"Flutter Mane", {"—"}},
        {"Slither Wing", {"—"}},
        {"Sandy Shocks", {"—"}},
        {"Iron Treads", {"—"}},
        {"Iron Bundle", {"—"}},
        {"Iron Hands", {"—"}},
        {"Iron Jugulis", {"—"}},
        {"Iron Moth", {"—"}},
        {"Iron Thorns", {"—"}},
        {"Frigibax", {"—"}},
        {"Arctibax", {"—"}},
        {"Baxcalibur", {"—"}},
        {"Gimmighoul", {"Chest","Roaming"}},
        {"Gholdengo", {"—"}},
        {"Wo-Chien", {"—"}},
        {"Chien-Pao", {"—"}},
        {"Ting-Lu", {"—"}},
        {"Chi-Yu", {"—"}},
        {"Roaring Moon", {"—"}},
        {"Iron Valiant", {"—"}},
        {"Koraidon", {"Apex","Limited","Sprinting","Swimming","Gliding"}},
        {"Miraidon", {"Ultimate","Low-Power","Drive","Aquatic","Glide"}},
        {"Walking Wake", {"—"}},
        {"Iron Leaves", {"—"}},
        {"Dipplin", {"—"}},
        {"Poltchageist", {"Counterfeit","Artisan"}},
        {"Sinistcha", {"Unremarkable","Masterpiece"}},
        {"Okidogi", {"—"}},
        {"Munkidori", {"—"}},
        {"Fezandipiti", {"—"}},
        {"Ogerpon", {"Teal","Wellspring","Hearthflame","Cornerstone"}},
        {"Archaludon", {"—"}},
        {"Hydrapple", {"—"}},
        {"Gouging Fire", {"—"}},
        {"Raging Bolt", {"—"}},
        {"Iron Boulder", {"—"}},
        {"Iron Crown", {"—"}},
        {"Terapagos", {"Normal","Terastal","Stellar"}},
        {"Pecharunt", {"—"}},
    };
private:
    // TODO


};


#endif // SHAREDRANDOMIZERWINDOW_H
