#ifndef SV_SHARED_CLASS_H
#define SV_SHARED_CLASS_H

#include "../qtwindows_headers/sharedRandomizerClass.h"

/*
    normal = normal
    kakutou = fightning
    hikou = flying
    doku = poison
    jimen = ground
    iwa = rock
    mushi = bug
    ghost = ghost
    hagane = steel
    honoo = fire
    mizu = water
    kusa = grass
    denki = electric
    esper = psychic
    koori = ice
    dragon = dragon
    aku = dark
    fairy = fairy (yousei everywhere else)
    niji = stellar
*/

class SVShared: public sharedRandomizerClass{

public:
    SVShared();
    ~SVShared();
    QDir qBaseDir;
    void patchFileDescriptor();
    QMap<QString, QStringList> nationalDexPokemonNamesAndForms = {
        {"Bulbasaur", {"—"}},
        {"Ivysaur", {"—"}},
        {"Venusaur", {"—"}},
        {"Charmander", {"—"}},
        {"Charmeleon", {"—"}},
        {"Charizard", {"—"}},
        {"Squirtle", {"—"}},
        {"Wartortle", {"—"}},
        {"Blastoise", {"—"}},
        {"Ekans", {"—"}},
        {"Arbok", {"—"}},
        {"Pikachu", {"Normal","Original","Hoenn","Sinnoh","Unova","Kalos","Alola","Partner","World"}},
        {"Raichu", {"Normal","Alolan"}},
        {"Sandshrew", {"Normal","Alolan"}},
        {"Sandslash", {"Normal","Alolan"}},
        {"Clefairy", {"—"}},
        {"Clefable", {"—"}},
        {"Vulpix", {"Normal","Alolan"}},
        {"Ninetales", {"Normal","Alolan"}},
        {"Jigglypuff", {"—"}},
        {"Wigglytuff", {"—"}},
        {"Oddish", {"—"}},
        {"Gloom", {"—"}},
        {"Vileplume", {"—"}},
        {"Venonat", {"—"}},
        {"Venomoth", {"—"}},
        {"Diglett", {"Normal","Alolan"}},
        {"Dugtrio", {"Normal","Alolan"}},
        {"Meowth", {"Normal","Alolan","Galarian"}},
        {"Persian", {"Normal","Alolan"}},
        {"Psyduck", {"—"}},
        {"Golduck", {"—"}},
        {"Mankey", {"—"}},
        {"Primeape", {"—"}},
        {"Growlithe", {"Normal","Hisuian"}},
        {"Arcanine", {"Normal","Hisuian"}},
        {"Poliwag", {"—"}},
        {"Poliwhirl", {"—"}},
        {"Poliwrath", {"—"}},
        {"Bellsprout", {"—"}},
        {"Weepinbell", {"—"}},
        {"Victreebel", {"—"}},
        {"Tentacool", {"—"}},
        {"Tentacruel", {"—"}},
        {"Geodude", {"Normal","Alolan"}},
        {"Graveler", {"Normal","Alolan"}},
        {"Golem", {"Normal","Alolan"}},
        {"Slowpoke", {"Normal","Galarian"}},
        {"Slowbro", {"Normal","Galarian"}},
        {"Magnemite", {"—"}},
        {"Magneton", {"—"}},
        {"Doduo", {"—"}},
        {"Dodrio", {"—"}},
        {"Seel", {"—"}},
        {"Dewgong", {"—"}},
        {"Grimer", {"Normal","Alolan"}},
        {"Muk", {"Normal","Alolan"}},
        {"Shellder", {"—"}},
        {"Cloyster", {"—"}},
        {"Gastly", {"—"}},
        {"Haunter", {"—"}},
        {"Gengar", {"—"}},
        {"Drowzee", {"—"}},
        {"Hypno", {"—"}},
        {"Voltorb", {"Normal","Hisuian"}},
        {"Electrode", {"Normal","Hisuian"}},
        {"Exeggcute", {"—"}},
        {"Exeggutor", {"Normal","Alolan"}},
        {"Hitmonlee", {"—"}},
        {"Hitmonchan", {"—"}},
        {"Koffing", {"—"}},
        {"Weezing", {"Normal","Galarian"}},
        {"Rhyhorn", {"—"}},
        {"Rhydon", {"—"}},
        {"Chansey", {"—"}},
        {"Horsea", {"—"}},
        {"Seadra", {"—"}},
        {"Scyther", {"—"}},
        {"Electabuzz", {"—"}},
        {"Magmar", {"—"}},
        {"Tauros", {"Normal","Paldean (Combat)","Paldean (Blaze)","Paldean (Aqua)"}},
        {"Magikarp", {"—"}},
        {"Gyarados", {"—"}},
        {"Lapras", {"—"}},
        {"Ditto", {"—"}},
        {"Eevee", {"—"}},
        {"Vaporeon", {"—"}},
        {"Jolteon", {"—"}},
        {"Flareon", {"—"}},
        {"Porygon", {"—"}},
        {"Snorlax", {"—"}},
        {"Articuno", {"Normal","Galarian"}},
        {"Zapdos", {"Normal","Galarian"}},
        {"Moltres", {"Normal","Galarian"}},
        {"Dratini", {"—"}},
        {"Dragonair", {"—"}},
        {"Dragonite", {"—"}},
        {"Mewtwo", {"—"}},
        {"Mew", {"—"}},
        {"Chikorita", {"—"}},
        {"Bayleef", {"—"}},
        {"Meganium", {"—"}},
        {"Cyndaquil", {"—"}},
        {"Quilava", {"—"}},
        {"Typhlosion", {"Normal","Hisuian"}},
        {"Totodile", {"—"}},
        {"Croconaw", {"—"}},
        {"Feraligatr", {"—"}},
        {"Sentret", {"—"}},
        {"Furret", {"—"}},
        {"Hoothoot", {"—"}},
        {"Noctowl", {"—"}},
        {"Spinarak", {"—"}},
        {"Ariados", {"—"}},
        {"Chinchou", {"—"}},
        {"Lanturn", {"—"}},
        {"Pichu", {"—"}},
        {"Cleffa", {"—"}},
        {"Igglybuff", {"—"}},
        {"Mareep", {"—"}},
        {"Flaaffy", {"—"}},
        {"Ampharos", {"—"}},
        {"Bellossom", {"—"}},
        {"Marill", {"—"}},
        {"Azumarill", {"—"}},
        {"Sudowoodo", {"—"}},
        {"Politoed", {"—"}},
        {"Hoppip", {"—"}},
        {"Skiploom", {"—"}},
        {"Jumpluff", {"—"}},
        {"Aipom", {"—"}},
        {"Sunkern", {"—"}},
        {"Sunflora", {"—"}},
        {"Yanma", {"—"}},
        {"Wooper", {"Normal","Paldean"}},
        {"Quagsire", {"—"}},
        {"Espeon", {"—"}},
        {"Umbreon", {"—"}},
        {"Murkrow", {"—"}},
        {"Slowking", {"Normal","Galarian"}},
        {"Misdreavus", {"—"}},
        {"Girafarig", {"—"}},
        {"Pineco", {"—"}},
        {"Forretress", {"—"}},
        {"Dunsparce", {"—"}},
        {"Gligar", {"—"}},
        {"Snubbull", {"—"}},
        {"Granbull", {"—"}},
        {"Qwilfish", {"Normal","Hisuian"}},
        {"Scizor", {"—"}},
        {"Heracross", {"—"}},
        {"Sneasel", {"Normal","Hisuian"}},
        {"Teddiursa", {"—"}},
        {"Ursaring", {"—"}},
        {"Slugma", {"—"}},
        {"Magcargo", {"—"}},
        {"Swinub", {"—"}},
        {"Piloswine", {"—"}},
        {"Delibird", {"—"}},
        {"Skarmory", {"—"}},
        {"Houndour", {"—"}},
        {"Houndoom", {"—"}},
        {"Kingdra", {"—"}},
        {"Phanpy", {"—"}},
        {"Donphan", {"—"}},
        {"Porygon2", {"—"}},
        {"Stantler", {"—"}},
        {"Smeargle", {"—"}},
        {"Tyrogue", {"—"}},
        {"Hitmontop", {"—"}},
        {"Elekid", {"—"}},
        {"Magby", {"—"}},
        {"Blissey", {"—"}},
        {"Raikou", {"—"}},
        {"Entei", {"—"}},
        {"Suicune", {"—"}},
        {"Larvitar", {"—"}},
        {"Pupitar", {"—"}},
        {"Tyranitar", {"—"}},
        {"Lugia", {"—"}},
        {"Ho-Oh", {"—"}},
        {"Treecko", {"—"}},
        {"Grovyle", {"—"}},
        {"Sceptile", {"—"}},
        {"Torchic", {"—"}},
        {"Combusken", {"—"}},
        {"Blaziken", {"—"}},
        {"Mudkip", {"—"}},
        {"Marshtomp", {"—"}},
        {"Swampert", {"—"}},
        {"Poochyena", {"—"}},
        {"Mightyena", {"—"}},
        {"Lotad", {"—"}},
        {"Lombre", {"—"}},
        {"Ludicolo", {"—"}},
        {"Seedot", {"—"}},
        {"Nuzleaf", {"—"}},
        {"Shiftry", {"—"}},
        {"Wingull", {"—"}},
        {"Pelipper", {"—"}},
        {"Ralts", {"—"}},
        {"Kirlia", {"—"}},
        {"Gardevoir", {"—"}},
        {"Surskit", {"—"}},
        {"Masquerain", {"—"}},
        {"Shroomish", {"—"}},
        {"Breloom", {"—"}},
        {"Slakoth", {"—"}},
        {"Vigoroth", {"—"}},
        {"Slaking", {"—"}},
        {"Makuhita", {"—"}},
        {"Hariyama", {"—"}},
        {"Azurill", {"—"}},
        {"Nosepass", {"—"}},
        {"Sableye", {"—"}},
        {"Meditite", {"—"}},
        {"Medicham", {"—"}},
        {"Plusle", {"—"}},
        {"Minun", {"—"}},
        {"Volbeat", {"—"}},
        {"Illumise", {"—"}},
        {"Gulpin", {"—"}},
        {"Swalot", {"—"}},
        {"Numel", {"—"}},
        {"Camerupt", {"—"}},
        {"Torkoal", {"—"}},
        {"Spoink", {"—"}},
        {"Grumpig", {"—"}},
        {"Trapinch", {"—"}},
        {"Vibrava", {"—"}},
        {"Flygon", {"—"}},
        {"Cacnea", {"—"}},
        {"Cacturne", {"—"}},
        {"Swablu", {"—"}},
        {"Altaria", {"—"}},
        {"Zangoose", {"—"}},
        {"Seviper", {"—"}},
        {"Barboach", {"—"}},
        {"Whiscash", {"—"}},
        {"Corphish", {"—"}},
        {"Crawdaunt", {"—"}},
        {"Feebas", {"—"}},
        {"Milotic", {"—"}},
        {"Shuppet", {"—"}},
        {"Banette", {"—"}},
        {"Duskull", {"—"}},
        {"Dusclops", {"—"}},
        {"Tropius", {"—"}},
        {"Chimecho", {"—"}},
        {"Snorunt", {"—"}},
        {"Glalie", {"—"}},
        {"Luvdisc", {"—"}},
        {"Bagon", {"—"}},
        {"Shelgon", {"—"}},
        {"Salamence", {"—"}},
        {"Beldum", {"—"}},
        {"Metang", {"—"}},
        {"Metagross", {"—"}},
        {"Regirock", {"—"}},
        {"Regice", {"—"}},
        {"Registeel", {"—"}},
        {"Latias", {"—"}},
        {"Latios", {"—"}},
        {"Kyogre", {"—"}},
        {"Groudon", {"—"}},
        {"Rayquaza", {"—"}},
        {"Jirachi", {"—"}},
        {"Deoxys", {"Normal","Attack","Defense","Speed"}},
        {"Turtwig", {"—"}},
        {"Grotle", {"—"}},
        {"Torterra", {"—"}},
        {"Chimchar", {"—"}},
        {"Monferno", {"—"}},
        {"Infernape", {"—"}},
        {"Piplup", {"—"}},
        {"Prinplup", {"—"}},
        {"Empoleon", {"—"}},
        {"Starly", {"—"}},
        {"Staravia", {"—"}},
        {"Staraptor", {"—"}},
        {"Kricketot", {"—"}},
        {"Kricketune", {"—"}},
        {"Shinx", {"—"}},
        {"Luxio", {"—"}},
        {"Luxray", {"—"}},
        {"Cranidos", {"—"}},
        {"Rampardos", {"—"}},
        {"Shieldon", {"—"}},
        {"Bastiodon", {"—"}},
        {"Combee", {"—"}},
        {"Vespiquen", {"—"}},
        {"Pachirisu", {"—"}},
        {"Buizel", {"—"}},
        {"Floatzel", {"—"}},
        {"Shellos", {"West","East"}},
        {"Gastrodon", {"West","East"}},
        {"Ambipom", {"—"}},
        {"Drifloon", {"—"}},
        {"Drifblim", {"—"}},
        {"Mismagius", {"—"}},
        {"Honchkrow", {"—"}},
        {"Chingling", {"—"}},
        {"Stunky", {"—"}},
        {"Skuntank", {"—"}},
        {"Bronzor", {"—"}},
        {"Bronzong", {"—"}},
        {"Bonsly", {"—"}},
        {"Happiny", {"—"}},
        {"Spiritomb", {"—"}},
        {"Gible", {"—"}},
        {"Gabite", {"—"}},
        {"Garchomp", {"—"}},
        {"Munchlax", {"—"}},
        {"Riolu", {"—"}},
        {"Lucario", {"—"}},
        {"Hippopotas", {"—"}},
        {"Hippowdon", {"—"}},
        {"Croagunk", {"—"}},
        {"Toxicroak", {"—"}},
        {"Finneon", {"—"}},
        {"Lumineon", {"—"}},
        {"Snover", {"—"}},
        {"Abomasnow", {"—"}},
        {"Weavile", {"—"}},
        {"Magnezone", {"—"}},
        {"Rhyperior", {"—"}},
        {"Electivire", {"—"}},
        {"Magmortar", {"—"}},
        {"Yanmega", {"—"}},
        {"Leafeon", {"—"}},
        {"Glaceon", {"—"}},
        {"Gliscor", {"—"}},
        {"Mamoswine", {"—"}},
        {"Porygon-Z", {"—"}},
        {"Gallade", {"—"}},
        {"Probopass", {"—"}},
        {"Dusknoir", {"—"}},
        {"Froslass", {"—"}},
        {"Rotom", {"Normal","Heat","Wash","Frost","Fan","Mow"}},
        {"Uxie", {"—"}},
        {"Mesprit", {"—"}},
        {"Azelf", {"—"}},
        {"Dialga", {"Normal","Origin"}},
        {"Palkia", {"Normal","Origin"}},
        {"Heatran", {"—"}},
        {"Regigigas", {"—"}},
        {"Giratina", {"Altered","Origin"}},
        {"Cresselia", {"—"}},
        {"Phione", {"—"}},
        {"Manaphy", {"—"}},
        {"Darkrai", {"—"}},
        {"Shaymin", {"Land","Sky"}},
        {"Arceus", {"Normal","Fighting","Flying","Poison","Ground","Rock","Bug","Ghost","Steel","Fire","Water","Grass","Electric","Psychic","Ice","Dragon","Dark","Fairy"}},
        {"Snivy", {"—"}},
        {"Servine", {"—"}},
        {"Serperior", {"—"}},
        {"Tepig", {"—"}},
        {"Pignite", {"—"}},
        {"Emboar", {"—"}},
        {"Oshawott", {"—"}},
        {"Dewott", {"—"}},
        {"Samurott", {"Normal","Hisuian"}},
        {"Blitzle", {"—"}},
        {"Zebstrika", {"—"}},
        {"Drilbur", {"—"}},
        {"Excadrill", {"—"}},
        {"Timburr", {"—"}},
        {"Gurdurr", {"—"}},
        {"Conkeldurr", {"—"}},
        {"Sewaddle", {"—"}},
        {"Swadloon", {"—"}},
        {"Leavanny", {"—"}},
        {"Cottonee", {"—"}},
        {"Whimsicott", {"—"}},
        {"Petilil", {"—"}},
        {"Lilligant", {"Normal","Hisuian"}},
        {"Basculin", {"Red","Blue","White"}},
        {"Sandile", {"—"}},
        {"Krokorok", {"—"}},
        {"Krookodile", {"—"}},
        {"Scraggy", {"—"}},
        {"Scrafty", {"—"}},
        {"Zorua", {"Normal","Hisuian"}},
        {"Zoroark", {"Normal","Hisuian"}},
        {"Minccino", {"—"}},
        {"Cinccino", {"—"}},
        {"Gothita", {"—"}},
        {"Gothorita", {"—"}},
        {"Gothitelle", {"—"}},
        {"Solosis", {"—"}},
        {"Duosion", {"—"}},
        {"Reuniclus", {"—"}},
        {"Ducklett", {"—"}},
        {"Swanna", {"—"}},
        {"Deerling", {"Spring","Summer","Autumn","Winter"}},
        {"Sawsbuck", {"Spring","Summer","Autumn","Winter"}},
        {"Foongus", {"—"}},
        {"Amoonguss", {"—"}},
        {"Alomomola", {"—"}},
        {"Joltik", {"—"}},
        {"Galvantula", {"—"}},
        {"Tynamo", {"—"}},
        {"Eelektrik", {"—"}},
        {"Eelektross", {"—"}},
        {"Litwick", {"—"}},
        {"Lampent", {"—"}},
        {"Chandelure", {"—"}},
        {"Axew", {"—"}},
        {"Fraxure", {"—"}},
        {"Haxorus", {"—"}},
        {"Cubchoo", {"—"}},
        {"Beartic", {"—"}},
        {"Cryogonal", {"—"}},
        {"Mienfoo", {"—"}},
        {"Mienshao", {"—"}},
        {"Golett", {"—"}},
        {"Golurk", {"—"}},
        {"Pawniard", {"—"}},
        {"Bisharp", {"—"}},
        {"Rufflet", {"—"}},
        {"Braviary", {"Normal","Hisuian"}},
        {"Vullaby", {"—"}},
        {"Mandibuzz", {"—"}},
        {"Deino", {"—"}},
        {"Zweilous", {"—"}},
        {"Hydreigon", {"—"}},
        {"Larvesta", {"—"}},
        {"Volcarona", {"—"}},
        {"Cobalion", {"—"}},
        {"Terrakion", {"—"}},
        {"Virizion", {"—"}},
        {"Tornadus", {"Incarnate","Therian"}},
        {"Thundurus", {"Incarnate","Therian"}},
        {"Reshiram", {"—"}},
        {"Zekrom", {"—"}},
        {"Landorus", {"Incarnate","Therian"}},
        {"Kyurem", {"Normal","White","Black"}},
        {"Keldeo", {"Ordinary","Resolute"}},
        {"Meloetta", {"Aria","Pirouette"}},
        {"Chespin", {"—"}},
        {"Quilladin", {"—"}},
        {"Chesnaught", {"—"}},
        {"Fennekin", {"—"}},
        {"Braixen", {"—"}},
        {"Delphox", {"—"}},
        {"Froakie", {"—"}},
        {"Frogadier", {"—"}},
        {"Greninja", {"Normal","Battle Bond"}},
        {"Fletchling", {"—"}},
        {"Fletchinder", {"—"}},
        {"Talonflame", {"—"}},
        {"Scatterbug", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Spewpa", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Vivillon", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Litleo", {"—"}},
        {"Pyroar", {"—"}},
        {"Flabébé", {"Red","Yellow","Orange","Blue","White"}},
        {"Floette", {"Red","Yellow","Orange","Blue","White"}},
        {"Florges", {"Red","Yellow","Orange","Blue","White"}},
        {"Skiddo", {"—"}},
        {"Gogoat", {"—"}},
        {"Espurr", {"—"}},
        {"Meowstic", {"Male","Female"}},
        {"Inkay", {"—"}},
        {"Malamar", {"—"}},
        {"Skrelp", {"—"}},
        {"Dragalge", {"—"}},
        {"Clauncher", {"—"}},
        {"Clawitzer", {"—"}},
        {"Sylveon", {"—"}},
        {"Hawlucha", {"—"}},
        {"Dedenne", {"—"}},
        {"Carbink", {"—"}},
        {"Goomy", {"—"}},
        {"Sliggoo", {"Normal","Hisuian"}},
        {"Goodra", {"Normal","Hisuian"}},
        {"Klefki", {"—"}},
        {"Phantump", {"—"}},
        {"Trevenant", {"—"}},
        {"Bergmite", {"—"}},
        {"Avalugg", {"Normal","Hisuian"}},
        {"Noibat", {"—"}},
        {"Noivern", {"—"}},
        {"Diancie", {"—"}},
        {"Hoopa", {"Confined","Unbound"}},
        {"Volcanion", {"—"}},
        {"Rowlet", {"—"}},
        {"Dartrix", {"—"}},
        {"Decidueye", {"Normal","Hisuian"}},
        {"Litten", {"—"}},
        {"Torracat", {"—"}},
        {"Incineroar", {"—"}},
        {"Popplio", {"—"}},
        {"Brionne", {"—"}},
        {"Primarina", {"—"}},
        {"Pikipek", {"—"}},
        {"Trumbeak", {"—"}},
        {"Toucannon", {"—"}},
        {"Yungoos", {"—"}},
        {"Gumshoos", {"—"}},
        {"Grubbin", {"—"}},
        {"Charjabug", {"—"}},
        {"Vikavolt", {"—"}},
        {"Crabrawler", {"—"}},
        {"Crabominable", {"—"}},
        {"Oricorio", {"Baile","Pom-Pom","Pa’u","Sensu"}},
        {"Cutiefly", {"—"}},
        {"Ribombee", {"—"}},
        {"Rockruff", {"Normal","Own Tempo"}},
        {"Lycanroc", {"Midday","Midnight","Dusk"}},
        {"Mareanie", {"—"}},
        {"Toxapex", {"—"}},
        {"Mudbray", {"—"}},
        {"Mudsdale", {"—"}},
        {"Dewpider", {"—"}},
        {"Araquanid", {"—"}},
        {"Fomantis", {"—"}},
        {"Lurantis", {"—"}},
        {"Salandit", {"—"}},
        {"Salazzle", {"—"}},
        {"Bounsweet", {"—"}},
        {"Steenee", {"—"}},
        {"Tsareena", {"—"}},
        {"Comfey", {"—"}},
        {"Oranguru", {"—"}},
        {"Passimian", {"—"}},
        {"Sandygast", {"—"}},
        {"Palossand", {"—"}},
        {"Minior", {"M-Red","M-Orange","M-Yellow","M-Green","M-Blue","M-Indigo","M-Violet","C-Red","C-Orange","C-Yellow","C-Green","C-Blue","C-Indigo","C-Violet"}},
        {"Komala", {"—"}},
        {"Mimikyu", {"Disguised","Busted"}},
        {"Bruxish", {"—"}},
        {"Jangmo-o", {"—"}},
        {"Hakamo-o", {"—"}},
        {"Kommo-o", {"—"}},
        {"Cosmog", {"—"}},
        {"Cosmoem", {"—"}},
        {"Solgaleo", {"—"}},
        {"Lunala", {"—"}},
        {"Necrozma", {"Normal","Dusk Mane","Dawn Wings"}},
        {"Magearna", {"Normal","Original"}},
        {"Grookey", {"—"}},
        {"Thwackey", {"—"}},
        {"Rillaboom", {"—"}},
        {"Scorbunny", {"—"}},
        {"Raboot", {"—"}},
        {"Cinderace", {"—"}},
        {"Sobble", {"—"}},
        {"Drizzile", {"—"}},
        {"Inteleon", {"—"}},
        {"Skwovet", {"—"}},
        {"Greedent", {"—"}},
        {"Rookidee", {"—"}},
        {"Corvisquire", {"—"}},
        {"Corviknight", {"—"}},
        {"Chewtle", {"—"}},
        {"Drednaw", {"—"}},
        {"Rolycoly", {"—"}},
        {"Carkol", {"—"}},
        {"Coalossal", {"—"}},
        {"Applin", {"—"}},
        {"Flapple", {"—"}},
        {"Appletun", {"—"}},
        {"Silicobra", {"—"}},
        {"Sandaconda", {"—"}},
        {"Cramorant", {"Normal","Gulping","Gorging"}},
        {"Arrokuda", {"—"}},
        {"Barraskewda", {"—"}},
        {"Toxel", {"—"}},
        {"Toxtricity", {"Amped","Low Key"}},
        {"Sinistea", {"Phony","Antique"}},
        {"Polteageist", {"Phony","Antique"}},
        {"Hatenna", {"—"}},
        {"Hattrem", {"—"}},
        {"Hatterene", {"—"}},
        {"Impidimp", {"—"}},
        {"Morgrem", {"—"}},
        {"Grimmsnarl", {"—"}},
        {"Perrserker", {"—"}},
        {"Milcery", {"—"}},
        {"Alcremie", {"Vanilla Cream","Ruby Cream","Matcha Cream","Mint Cream","Lemon Cream","Salted Cream","Ruby Swirl","Caramel Swirl","Rainbow Swirl"}},
        {"Falinks", {"—"}},
        {"Pincurchin", {"—"}},
        {"Snom", {"—"}},
        {"Frosmoth", {"—"}},
        {"Stonjourner", {"—"}},
        {"Eiscue", {"Ice Face","Noice Face"}},
        {"Indeedee", {"Male","Female"}},
        {"Morpeko", {"Full Belly","Hangry"}},
        {"Cufant", {"—"}},
        {"Copperajah", {"—"}},
        {"Duraludon", {"—"}},
        {"Dreepy", {"—"}},
        {"Drakloak", {"—"}},
        {"Dragapult", {"—"}},
        {"Zacian", {"Hero","Crowned"}},
        {"Zamazenta", {"Hero","Crowned"}},
        {"Eternatus", {"—"}},
        {"Kubfu", {"—"}},
        {"Urshifu", {"Single","Rapid"}},
        {"Zarude", {"Normal","Dada"}},
        {"Regieleki", {"—"}},
        {"Regidrago", {"—"}},
        {"Glastrier", {"—"}},
        {"Spectrier", {"—"}},
        {"Calyrex", {"Normal","Ice","Shadow"}},
        {"Wyrdeer", {"—"}},
        {"Kleavor", {"—"}},
        {"Ursaluna", {"Normal","Bloodmoon"}},
        {"Basculegion", {"Male","Female"}},
        {"Sneasler", {"—"}},
        {"Overqwil", {"—"}},
        {"Enamorus", {"Incarnate","Therian"}},
        {"Sprigatito", {"—"}},
        {"Floragato", {"—"}},
        {"Meowscarada", {"—"}},
        {"Fuecoco", {"—"}},
        {"Crocalor", {"—"}},
        {"Skeledirge", {"—"}},
        {"Quaxly", {"—"}},
        {"Quaxwell", {"—"}},
        {"Quaquaval", {"—"}},
        {"Lechonk", {"—"}},
        {"Oinkologne", {"Male","Female"}},
        {"Tarountula", {"—"}},
        {"Spidops", {"—"}},
        {"Nymble", {"—"}},
        {"Lokix", {"—"}},
        {"Pawmi", {"—"}},
        {"Pawmo", {"—"}},
        {"Pawmot", {"—"}},
        {"Tandemaus", {"—"}},
        {"Maushold", {"Three","Four"}},
        {"Fidough", {"—"}},
        {"Dachsbun", {"—"}},
        {"Smoliv", {"—"}},
        {"Dolliv", {"—"}},
        {"Arboliva", {"—"}},
        {"Squawkabilly", {"Green","Blue","Yellow","White"}},
        {"Nacli", {"—"}},
        {"Naclstack", {"—"}},
        {"Garganacl", {"—"}},
        {"Charcadet", {"—"}},
        {"Armarouge", {"—"}},
        {"Ceruledge", {"—"}},
        {"Tadbulb", {"—"}},
        {"Bellibolt", {"—"}},
        {"Wattrel", {"—"}},
        {"Kilowattrel", {"—"}},
        {"Maschiff", {"—"}},
        {"Mabosstiff", {"—"}},
        {"Shroodle", {"—"}},
        {"Grafaiai", {"—"}},
        {"Bramblin", {"—"}},
        {"Brambleghast", {"—"}},
        {"Toedscool", {"—"}},
        {"Toedscruel", {"—"}},
        {"Klawf", {"—"}},
        {"Capsakid", {"—"}},
        {"Scovillain", {"—"}},
        {"Rellor", {"—"}},
        {"Rabsca", {"—"}},
        {"Flittle", {"—"}},
        {"Espathra", {"—"}},
        {"Tinkatink", {"—"}},
        {"Tinkatuff", {"—"}},
        {"Tinkaton", {"—"}},
        {"Wiglett", {"—"}},
        {"Wugtrio", {"—"}},
        {"Bombirdier", {"—"}},
        {"Finizen", {"—"}},
        {"Palafin", {"Zero","Hero"}},
        {"Varoom", {"—"}},
        {"Revavroom", {"—"}},
        {"Cyclizar", {"—"}},
        {"Orthworm", {"—"}},
        {"Glimmet", {"—"}},
        {"Glimmora", {"—"}},
        {"Greavard", {"—"}},
        {"Houndstone", {"—"}},
        {"Flamigo", {"—"}},
        {"Cetoddle", {"—"}},
        {"Cetitan", {"—"}},
        {"Veluza", {"—"}},
        {"Dondozo", {"—"}},
        {"Tatsugiri", {"Curly","Droopy","Stretchy"}},
        {"Annihilape", {"—"}},
        {"Clodsire", {"—"}},
        {"Farigiraf", {"—"}},
        {"Dudunsparce", {"Two","Three"}},
        {"Kingambit", {"—"}},
        {"Great Tusk", {"—"}},
        {"Scream Tail", {"—"}},
        {"Brute Bonnet", {"—"}},
        {"Flutter Mane", {"—"}},
        {"Slither Wing", {"—"}},
        {"Sandy Shocks", {"—"}},
        {"Iron Treads", {"—"}},
        {"Iron Bundle", {"—"}},
        {"Iron Hands", {"—"}},
        {"Iron Jugulis", {"—"}},
        {"Iron Moth", {"—"}},
        {"Iron Thorns", {"—"}},
        {"Frigibax", {"—"}},
        {"Arctibax", {"—"}},
        {"Baxcalibur", {"—"}},
        {"Gimmighoul", {"Chest","Roaming"}},
        {"Gholdengo", {"—"}},
        {"Wo-Chien", {"—"}},
        {"Chien-Pao", {"—"}},
        {"Ting-Lu", {"—"}},
        {"Chi-Yu", {"—"}},
        {"Roaring Moon", {"—"}},
        {"Iron Valiant", {"—"}},
        {"Koraidon", {"Apex","Limited","Sprinting","Swimming","Gliding"}},
        {"Miraidon", {"Ultimate","Low-Power","Drive","Aquatic","Glide"}},
        {"Walking Wake", {"—"}},
        {"Iron Leaves", {"—"}},
        {"Dipplin", {"—"}},
        {"Poltchageist", {"Counterfeit","Artisan"}},
        {"Sinistcha", {"Unremarkable","Masterpiece"}},
        {"Okidogi", {"—"}},
        {"Munkidori", {"—"}},
        {"Fezandipiti", {"—"}},
        {"Ogerpon", {"Teal","Wellspring","Hearthflame","Cornerstone"}},
        {"Archaludon", {"—"}},
        {"Hydrapple", {"—"}},
        {"Gouging Fire", {"—"}},
        {"Raging Bolt", {"—"}},
        {"Iron Boulder", {"—"}},
        {"Iron Crown", {"—"}},
        {"Terapagos", {"Normal","Terastal","Stellar"}},
        {"Pecharunt", {"—"}},
    };
    QStringList pokemonInGame ={
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Drowzee",
        "Hypno",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Hitmonlee",
        "Hitmonchan",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Horsea",
        "Seadra",
        "Scyther",
        "Electabuzz",
        "Magmar",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Spinarak",
        "Ariados",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Delibird",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Elekid",
        "Magby",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-Oh",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Sableye",
        "Meditite",
        "Medicham",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Gulpin",
        "Swalot",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Feebas",
        "Milotic",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Snorunt",
        "Glalie",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Mismagius",
        "Honchkrow",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "Happiny",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Croagunk",
        "Toxicroak",
        "Finneon",
        "Lumineon",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Rhyperior",
        "Electivire",
        "Magmortar",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "Porygon-Z",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Blitzle",
        "Zebstrika",
        "Drilbur",
        "Excadrill",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Scraggy",
        "Scrafty",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Deerling",
        "Sawsbuck",
        "Foongus",
        "Amoonguss",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Mienfoo",
        "Mienshao",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabébé",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Espurr",
        "Meowstic",
        "Inkay",
        "Malamar",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Diancie",
        "Hoopa",
        "Volcanion",
        "Rowlet",
        "Dartrix",
        "Decidueye",
        "Litten",
        "Torracat",
        "Incineroar",
        "Popplio",
        "Brionne",
        "Primarina",
        "Pikipek",
        "Trumbeak",
        "Toucannon",
        "Yungoos",
        "Gumshoos",
        "Grubbin",
        "Charjabug",
        "Vikavolt",
        "Crabrawler",
        "Crabominable",
        "Oricorio",
        "Cutiefly",
        "Ribombee",
        "Rockruff",
        "Lycanroc",
        "Mareanie",
        "Toxapex",
        "Mudbray",
        "Mudsdale",
        "Dewpider",
        "Araquanid",
        "Fomantis",
        "Lurantis",
        "Salandit",
        "Salazzle",
        "Bounsweet",
        "Steenee",
        "Tsareena",
        "Comfey",
        "Oranguru",
        "Passimian",
        "Sandygast",
        "Palossand",
        "Minior",
        "Komala",
        "Mimikyu",
        "Bruxish",
        "Jangmo-o",
        "Hakamo-o",
        "Kommo-o",
        "Cosmog",
        "Cosmoem",
        "Solgaleo",
        "Lunala",
        "Necrozma",
        "Magearna",
        "Grookey",
        "Thwackey",
        "Rillaboom",
        "Scorbunny",
        "Raboot",
        "Cinderace",
        "Sobble",
        "Drizzile",
        "Inteleon",
        "Skwovet",
        "Greedent",
        "Rookidee",
        "Corvisquire",
        "Corviknight",
        "Chewtle",
        "Drednaw",
        "Rolycoly",
        "Carkol",
        "Coalossal",
        "Applin",
        "Flapple",
        "Appletun",
        "Silicobra",
        "Sandaconda",
        "Cramorant",
        "Arrokuda",
        "Barraskewda",
        "Toxel",
        "Toxtricity",
        "Sinistea",
        "Polteageist",
        "Hatenna",
        "Hattrem",
        "Hatterene",
        "Impidimp",
        "Morgrem",
        "Grimmsnarl",
        "Perrserker",
        "Milcery",
        "Alcremie",
        "Falinks",
        "Pincurchin",
        "Snom",
        "Frosmoth",
        "Stonjourner",
        "Eiscue",
        "Indeedee",
        "Morpeko",
        "Cufant",
        "Copperajah",
        "Duraludon",
        "Dreepy",
        "Drakloak",
        "Dragapult",
        "Zacian",
        "Zamazenta",
        "Eternatus",
        "Kubfu",
        "Urshifu",
        "Zarude",
        "Regieleki",
        "Regidrago",
        "Glastrier",
        "Spectrier",
        "Calyrex",
        "Wyrdeer",
        "Kleavor",
        "Ursaluna",
        "Basculegion",
        "Sneasler",
        "Overqwil",
        "Enamorus",
        "Sprigatito",
        "Floragato",
        "Meowscarada",
        "Fuecoco",
        "Crocalor",
        "Skeledirge",
        "Quaxly",
        "Quaxwell",
        "Quaquaval",
        "Lechonk",
        "Oinkologne",
        "Tarountula",
        "Spidops",
        "Nymble",
        "Lokix",
        "Pawmi",
        "Pawmo",
        "Pawmot",
        "Tandemaus",
        "Maushold",
        "Fidough",
        "Dachsbun",
        "Smoliv",
        "Dolliv",
        "Arboliva",
        "Squawkabilly",
        "Nacli",
        "Naclstack",
        "Garganacl",
        "Charcadet",
        "Armarouge",
        "Ceruledge",
        "Tadbulb",
        "Bellibolt",
        "Wattrel",
        "Kilowattrel",
        "Maschiff",
        "Mabosstiff",
        "Shroodle",
        "Grafaiai",
        "Bramblin",
        "Brambleghast",
        "Toedscool",
        "Toedscruel",
        "Klawf",
        "Capsakid",
        "Scovillain",
        "Rellor",
        "Rabsca",
        "Flittle",
        "Espathra",
        "Tinkatink",
        "Tinkatuff",
        "Tinkaton",
        "Wiglett",
        "Wugtrio",
        "Bombirdier",
        "Finizen",
        "Palafin",
        "Varoom",
        "Revavroom",
        "Cyclizar",
        "Orthworm",
        "Glimmet",
        "Glimmora",
        "Greavard",
        "Houndstone",
        "Flamigo",
        "Cetoddle",
        "Cetitan",
        "Veluza",
        "Dondozo",
        "Tatsugiri",
        "Annihilape",
        "Clodsire",
        "Farigiraf",
        "Dudunsparce",
        "Kingambit",
        "Great Tusk",
        "Scream Tail",
        "Brute Bonnet",
        "Flutter Mane",
        "Slither Wing",
        "Sandy Shocks",
        "Iron Treads",
        "Iron Bundle",
        "Iron Hands",
        "Iron Jugulis",
        "Iron Moth",
        "Iron Thorns",
        "Frigibax",
        "Arctibax",
        "Baxcalibur",
        "Gimmighoul",
        "Gholdengo",
        "Wo-Chien",
        "Chien-Pao",
        "Ting-Lu",
        "Chi-Yu",
        "Roaring Moon",
        "Iron Valiant",
        "Koraidon",
        "Miraidon",
        "Walking Wake",
        "Iron Leaves",
        "Dipplin",
        "Poltchageist",
        "Sinistcha",
        "Okidogi",
        "Munkidori",
        "Fezandipiti",
        "Ogerpon",
        "Archaludon",
        "Hydrapple",
        "Gouging Fire",
        "Raging Bolt",
        "Iron Boulder",
        "Iron Crown",
        "Terapagos",
        "Pecharunt" };
    QMap<QString, QList<int>> pokemonFormsIntsInGame = {
        {"",{0}},
        {"Bulbasaur", {0}},
        {"Ivysaur", {0}},
        {"Venusaur", {0}},
        {"Charmander", {0}},
        {"Charmeleon", {0}},
        {"Charizard", {0}},
        {"Squirtle", {0}},
        {"Wartortle", {0}},
        {"Blastoise", {0}},
        {"Ekans", {0}},
        {"Arbok", {0}},
        {"Pikachu", {0,1,2,3,4,5,6,7,9}},
        {"Raichu", {0,1}},
        {"Sandshrew", {0,1}},
        {"Sandslash", {0,1}},
        {"Clefairy", {0}},
        {"Clefable", {0}},
        {"Vulpix", {0,1}},
        {"Ninetales", {0,1}},
        {"Jigglypuff", {0}},
        {"Wigglytuff", {0}},
        {"Oddish", {0}},
        {"Gloom", {0}},
        {"Vileplume", {0}},
        {"Venonat", {0}},
        {"Venomoth", {0}},
        {"Diglett", {0,1}},
        {"Dugtrio", {0,1}},
        {"Meowth", {0,1,2}},
        {"Persian", {0,1}},
        {"Psyduck", {0}},
        {"Golduck", {0}},
        {"Mankey", {0}},
        {"Primeape", {0}},
        {"Growlithe", {0,1}},
        {"Arcanine", {0,1}},
        {"Poliwag", {0}},
        {"Poliwhirl", {0}},
        {"Poliwrath", {0}},
        {"Bellsprout", {0}},
        {"Weepinbell", {0}},
        {"Victreebel", {0}},
        {"Tentacool", {0}},
        {"Tentacruel", {0}},
        {"Geodude", {0,1}},
        {"Graveler", {0,1}},
        {"Golem", {0,1}},
        {"Slowpoke", {0,1}},
        {"Slowbro", {0,2}},
        {"Magnemite", {0}},
        {"Magneton", {0}},
        {"Doduo", {0}},
        {"Dodrio", {0}},
        {"Seel", {0}},
        {"Dewgong", {0}},
        {"Grimer", {0,1}},
        {"Muk", {0,1}},
        {"Shellder", {0}},
        {"Cloyster", {0}},
        {"Gastly", {0}},
        {"Haunter", {0}},
        {"Gengar", {0}},
        {"Drowzee", {0}},
        {"Hypno", {0}},
        {"Voltorb", {0,1}},
        {"Electrode", {0,1}},
        {"Exeggcute", {0}},
        {"Exeggutor", {0,1}},
        {"Hitmonlee", {0}},
        {"Hitmonchan", {0}},
        {"Koffing", {0}},
        {"Weezing", {0,1}},
        {"Rhyhorn", {0}},
        {"Rhydon", {0}},
        {"Chansey", {0}},
        {"Horsea", {0}},
        {"Seadra", {0}},
        {"Scyther", {0}},
        {"Electabuzz", {0}},
        {"Magmar", {0}},
        {"Tauros", {0,1,2,3}},
        {"Magikarp", {0}},
        {"Gyarados", {0}},
        {"Lapras", {0}},
        {"Ditto", {0}},
        {"Eevee", {0}},
        {"Vaporeon", {0}},
        {"Jolteon", {0}},
        {"Flareon", {0}},
        {"Porygon", {0}},
        {"Snorlax", {0}},
        {"Articuno", {0,1}},
        {"Zapdos", {0,1}},
        {"Moltres", {0,1}},
        {"Dratini", {0}},
        {"Dragonair", {0}},
        {"Dragonite", {0}},
        {"Mewtwo", {0}},
        {"Mew", {0}},
        {"Chikorita", {0}},
        {"Bayleef", {0}},
        {"Meganium", {0}},
        {"Cyndaquil", {0}},
        {"Quilava", {0}},
        {"Typhlosion", {0,1}},
        {"Totodile", {0}},
        {"Croconaw", {0}},
        {"Feraligatr", {0}},
        {"Sentret", {0}},
        {"Furret", {0}},
        {"Hoothoot", {0}},
        {"Noctowl", {0}},
        {"Spinarak", {0}},
        {"Ariados", {0}},
        {"Chinchou", {0}},
        {"Lanturn", {0}},
        {"Pichu", {0}},
        {"Cleffa", {0}},
        {"Igglybuff", {0}},
        {"Mareep", {0}},
        {"Flaaffy", {0}},
        {"Ampharos", {0}},
        {"Bellossom", {0}},
        {"Marill", {0}},
        {"Azumarill", {0}},
        {"Sudowoodo", {0}},
        {"Politoed", {0}},
        {"Hoppip", {0}},
        {"Skiploom", {0}},
        {"Jumpluff", {0}},
        {"Aipom", {0}},
        {"Sunkern", {0}},
        {"Sunflora", {0}},
        {"Yanma", {0}},
        {"Wooper", {0,1}},
        {"Quagsire", {0}},
        {"Espeon", {0}},
        {"Umbreon", {0}},
        {"Murkrow", {0}},
        {"Slowking", {0,1}},
        {"Misdreavus", {0}},
        {"Girafarig", {0}},
        {"Pineco", {0}},
        {"Forretress", {0}},
        {"Dunsparce", {0}},
        {"Gligar", {0}},
        {"Snubbull", {0}},
        {"Granbull", {0}},
        {"Qwilfish", {0,1}},
        {"Scizor", {0}},
        {"Heracross", {0}},
        {"Sneasel", {0,1}},
        {"Teddiursa", {0}},
        {"Ursaring", {0}},
        {"Slugma", {0}},
        {"Magcargo", {0}},
        {"Swinub", {0}},
        {"Piloswine", {0}},
        {"Delibird", {0}},
        {"Skarmory", {0}},
        {"Houndour", {0}},
        {"Houndoom", {0}},
        {"Kingdra", {0}},
        {"Phanpy", {0}},
        {"Donphan", {0}},
        {"Porygon2", {0}},
        {"Stantler", {0}},
        {"Smeargle", {0}},
        {"Tyrogue", {0}},
        {"Hitmontop", {0}},
        {"Elekid", {0}},
        {"Magby", {0}},
        {"Blissey", {0}},
        {"Raikou", {0}},
        {"Entei", {0}},
        {"Suicune", {0}},
        {"Larvitar", {0}},
        {"Pupitar", {0}},
        {"Tyranitar", {0}},
        {"Lugia", {0}},
        {"Ho-Oh", {0}},
        {"Treecko", {0}},
        {"Grovyle", {0}},
        {"Sceptile", {0}},
        {"Torchic", {0}},
        {"Combusken", {0}},
        {"Blaziken", {0}},
        {"Mudkip", {0}},
        {"Marshtomp", {0}},
        {"Swampert", {0}},
        {"Poochyena", {0}},
        {"Mightyena", {0}},
        {"Lotad", {0}},
        {"Lombre", {0}},
        {"Ludicolo", {0}},
        {"Seedot", {0}},
        {"Nuzleaf", {0}},
        {"Shiftry", {0}},
        {"Wingull", {0}},
        {"Pelipper", {0}},
        {"Ralts", {0}},
        {"Kirlia", {0}},
        {"Gardevoir", {0}},
        {"Surskit", {0}},
        {"Masquerain", {0}},
        {"Shroomish", {0}},
        {"Breloom", {0}},
        {"Slakoth", {0}},
        {"Vigoroth", {0}},
        {"Slaking", {0}},
        {"Makuhita", {0}},
        {"Hariyama", {0}},
        {"Azurill", {0}},
        {"Nosepass", {0}},
        {"Sableye", {0}},
        {"Meditite", {0}},
        {"Medicham", {0}},
        {"Plusle", {0}},
        {"Minun", {0}},
        {"Volbeat", {0}},
        {"Illumise", {0}},
        {"Gulpin", {0}},
        {"Swalot", {0}},
        {"Numel", {0}},
        {"Camerupt", {0}},
        {"Torkoal", {0}},
        {"Spoink", {0}},
        {"Grumpig", {0}},
        {"Trapinch", {0}},
        {"Vibrava", {0}},
        {"Flygon", {0}},
        {"Cacnea", {0}},
        {"Cacturne", {0}},
        {"Swablu", {0}},
        {"Altaria", {0}},
        {"Zangoose", {0}},
        {"Seviper", {0}},
        {"Barboach", {0}},
        {"Whiscash", {0}},
        {"Corphish", {0}},
        {"Crawdaunt", {0}},
        {"Feebas", {0}},
        {"Milotic", {0}},
        {"Shuppet", {0}},
        {"Banette", {0}},
        {"Duskull", {0}},
        {"Dusclops", {0}},
        {"Tropius", {0}},
        {"Chimecho", {0}},
        {"Snorunt", {0}},
        {"Glalie", {0}},
        {"Luvdisc", {0}},
        {"Bagon", {0}},
        {"Shelgon", {0}},
        {"Salamence", {0}},
        {"Beldum", {0}},
        {"Metang", {0}},
        {"Metagross", {0}},
        {"Regirock", {0}},
        {"Regice", {0}},
        {"Registeel", {0}},
        {"Latias", {0}},
        {"Latios", {0}},
        {"Kyogre", {0}},
        {"Groudon", {0}},
        {"Rayquaza", {0}},
        {"Jirachi", {0}},
        {"Deoxys", {0,1,2,3}},
        {"Turtwig", {0}},
        {"Grotle", {0}},
        {"Torterra", {0}},
        {"Chimchar", {0}},
        {"Monferno", {0}},
        {"Infernape", {0}},
        {"Piplup", {0}},
        {"Prinplup", {0}},
        {"Empoleon", {0}},
        {"Starly", {0}},
        {"Staravia", {0}},
        {"Staraptor", {0}},
        {"Kricketot", {0}},
        {"Kricketune", {0}},
        {"Shinx", {0}},
        {"Luxio", {0}},
        {"Luxray", {0}},
        {"Cranidos", {0}},
        {"Rampardos", {0}},
        {"Shieldon", {0}},
        {"Bastiodon", {0}},
        {"Combee", {0}},
        {"Vespiquen", {0}},
        {"Pachirisu", {0}},
        {"Buizel", {0}},
        {"Floatzel", {0}},
        {"Shellos", {0,1}},
        {"Gastrodon", {0,1}},
        {"Ambipom", {0}},
        {"Drifloon", {0}},
        {"Drifblim", {0}},
        {"Mismagius", {0}},
        {"Honchkrow", {0}},
        {"Chingling", {0}},
        {"Stunky", {0}},
        {"Skuntank", {0}},
        {"Bronzor", {0}},
        {"Bronzong", {0}},
        {"Bonsly", {0}},
        {"Happiny", {0}},
        {"Spiritomb", {0}},
        {"Gible", {0}},
        {"Gabite", {0}},
        {"Garchomp", {0}},
        {"Munchlax", {0}},
        {"Riolu", {0}},
        {"Lucario", {0}},
        {"Hippopotas", {0}},
        {"Hippowdon", {0}},
        {"Croagunk", {0}},
        {"Toxicroak", {0}},
        {"Finneon", {0}},
        {"Lumineon", {0}},
        {"Snover", {0}},
        {"Abomasnow", {0}},
        {"Weavile", {0}},
        {"Magnezone", {0}},
        {"Rhyperior", {0}},
        {"Electivire", {0}},
        {"Magmortar", {0}},
        {"Yanmega", {0}},
        {"Leafeon", {0}},
        {"Glaceon", {0}},
        {"Gliscor", {0}},
        {"Mamoswine", {0}},
        {"Porygon-Z", {0}},
        {"Gallade", {0}},
        {"Probopass", {0}},
        {"Dusknoir", {0}},
        {"Froslass", {0}},
        {"Rotom", {0,1,2,3,4,5}},
        {"Uxie", {0}},
        {"Mesprit", {0}},
        {"Azelf", {0}},
        {"Dialga", {0,1}},
        {"Palkia", {0,1}},
        {"Heatran", {0}},
        {"Regigigas", {0}},
        {"Giratina", {0,1}},
        {"Cresselia", {0}},
        {"Phione", {0}},
        {"Manaphy", {0}},
        {"Darkrai", {0}},
        {"Shaymin", {0,1}},
        {"Arceus", {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17}},
        {"Snivy", {0}},
        {"Servine", {0}},
        {"Serperior", {0}},
        {"Tepig", {0}},
        {"Pignite", {0}},
        {"Emboar", {0}},
        {"Oshawott", {0}},
        {"Dewott", {0}},
        {"Samurott", {0,1}},
        {"Blitzle", {0}},
        {"Zebstrika", {0}},
        {"Drilbur", {0}},
        {"Excadrill", {0}},
        {"Timburr", {0}},
        {"Gurdurr", {0}},
        {"Conkeldurr", {0}},
        {"Sewaddle", {0}},
        {"Swadloon", {0}},
        {"Leavanny", {0}},
        {"Cottonee", {0}},
        {"Whimsicott", {0}},
        {"Petilil", {0}},
        {"Lilligant", {0,1}},
        {"Basculin", {0,1,2}},
        {"Sandile", {0}},
        {"Krokorok", {0}},
        {"Krookodile", {0}},
        {"Scraggy", {0}},
        {"Scrafty", {0}},
        {"Zorua", {0,1}},
        {"Zoroark", {0,1}},
        {"Minccino", {0}},
        {"Cinccino", {0}},
        {"Gothita", {0}},
        {"Gothorita", {0}},
        {"Gothitelle", {0}},
        {"Solosis", {0}},
        {"Duosion", {0}},
        {"Reuniclus", {0}},
        {"Ducklett", {0}},
        {"Swanna", {0}},
        {"Deerling", {0,1,2,3}},
        {"Sawsbuck", {0,1,2,3}},
        {"Foongus", {0}},
        {"Amoonguss", {0}},
        {"Alomomola", {0}},
        {"Joltik", {0}},
        {"Galvantula", {0}},
        {"Tynamo", {0}},
        {"Eelektrik", {0}},
        {"Eelektross", {0}},
        {"Litwick", {0}},
        {"Lampent", {0}},
        {"Chandelure", {0}},
        {"Axew", {0}},
        {"Fraxure", {0}},
        {"Haxorus", {0}},
        {"Cubchoo", {0}},
        {"Beartic", {0}},
        {"Cryogonal", {0}},
        {"Mienfoo", {0}},
        {"Mienshao", {0}},
        {"Golett", {0}},
        {"Golurk", {0}},
        {"Pawniard", {0}},
        {"Bisharp", {0}},
        {"Rufflet", {0}},
        {"Braviary", {0,1}},
        {"Vullaby", {0}},
        {"Mandibuzz", {0}},
        {"Deino", {0}},
        {"Zweilous", {0}},
        {"Hydreigon", {0}},
        {"Larvesta", {0}},
        {"Volcarona", {0}},
        {"Cobalion", {0}},
        {"Terrakion", {0}},
        {"Virizion", {0}},
        {"Tornadus", {0,1}},
        {"Thundurus", {0,1}},
        {"Reshiram", {0}},
        {"Zekrom", {0}},
        {"Landorus", {0,1}},
        {"Kyurem", {0,1,2}},
        {"Keldeo", {0,1}},
        {"Meloetta", {0,1}},
        {"Chespin", {0}},
        {"Quilladin", {0}},
        {"Chesnaught", {0}},
        {"Fennekin", {0}},
        {"Braixen", {0}},
        {"Delphox", {0}},
        {"Froakie", {0}},
        {"Frogadier", {0}},
        {"Greninja", {0,1}},
        {"Fletchling", {0}},
        {"Fletchinder", {0}},
        {"Talonflame", {0}},
        {"Scatterbug", {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19}},
        {"Spewpa", {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19}},
        {"Vivillon", {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19}},
        {"Litleo", {0}},
        {"Pyroar", {0}},
        {"Flabébé", {0,1,2,3,4}},
        {"Floette", {0,1,2,3,4}},
        {"Florges", {0,1,2,3,4}},
        {"Skiddo", {0}},
        {"Gogoat", {0}},
        {"Espurr", {0}},
        {"Meowstic", {0,1}},
        {"Inkay", {0}},
        {"Malamar", {0}},
        {"Skrelp", {0}},
        {"Dragalge", {0}},
        {"Clauncher", {0}},
        {"Clawitzer", {0}},
        {"Sylveon", {0}},
        {"Hawlucha", {0}},
        {"Dedenne", {0}},
        {"Carbink", {0}},
        {"Goomy", {0}},
        {"Sliggoo", {0,1}},
        {"Goodra", {0,1}},
        {"Klefki", {0}},
        {"Phantump", {0}},
        {"Trevenant", {0}},
        {"Bergmite", {0}},
        {"Avalugg", {0,1}},
        {"Noibat", {0}},
        {"Noivern", {0}},
        {"Diancie", {0}},
        {"Hoopa", {0,1}},
        {"Volcanion", {0}},
        {"Rowlet", {0}},
        {"Dartrix", {0}},
        {"Decidueye", {0,1}},
        {"Litten", {0}},
        {"Torracat", {0}},
        {"Incineroar", {0}},
        {"Popplio", {0}},
        {"Brionne", {0}},
        {"Primarina", {0}},
        {"Pikipek", {0}},
        {"Trumbeak", {0}},
        {"Toucannon", {0}},
        {"Yungoos", {0}},
        {"Gumshoos", {0}},
        {"Grubbin", {0}},
        {"Charjabug", {0}},
        {"Vikavolt", {0}},
        {"Crabrawler", {0}},
        {"Crabominable", {0}},
        {"Oricorio", {0,1,2,3}},
        {"Cutiefly", {0}},
        {"Ribombee", {0}},
        {"Rockruff", {0,1}},
        {"Lycanroc", {0,1,2}},
        {"Mareanie", {0}},
        {"Toxapex", {0}},
        {"Mudbray", {0}},
        {"Mudsdale", {0}},
        {"Dewpider", {0}},
        {"Araquanid", {0}},
        {"Fomantis", {0}},
        {"Lurantis", {0}},
        {"Salandit", {0}},
        {"Salazzle", {0}},
        {"Bounsweet", {0}},
        {"Steenee", {0}},
        {"Tsareena", {0}},
        {"Comfey", {0}},
        {"Oranguru", {0}},
        {"Passimian", {0}},
        {"Sandygast", {0}},
        {"Palossand", {0}},
        {"Minior", {0,1,2,3,4,5,6,7,8,9,10,11,12,13}},
        {"Komala", {0}},
        {"Mimikyu", {0,1}},
        {"Bruxish", {0}},
        {"Jangmo-o", {0}},
        {"Hakamo-o", {0}},
        {"Kommo-o", {0}},
        {"Cosmog", {0}},
        {"Cosmoem", {0}},
        {"Solgaleo", {0}},
        {"Lunala", {0}},
        {"Necrozma", {0,1,2}},
        {"Magearna", {0,1}},
        {"Grookey", {0}},
        {"Thwackey", {0}},
        {"Rillaboom", {0}},
        {"Scorbunny", {0}},
        {"Raboot", {0}},
        {"Cinderace", {0}},
        {"Sobble", {0}},
        {"Drizzile", {0}},
        {"Inteleon", {0}},
        {"Skwovet", {0}},
        {"Greedent", {0}},
        {"Rookidee", {0}},
        {"Corvisquire", {0}},
        {"Corviknight", {0}},
        {"Chewtle", {0}},
        {"Drednaw", {0}},
        {"Rolycoly", {0}},
        {"Carkol", {0}},
        {"Coalossal", {0}},
        {"Applin", {0}},
        {"Flapple", {0}},
        {"Appletun", {0}},
        {"Silicobra", {0}},
        {"Sandaconda", {0}},
        {"Cramorant", {0,1,2}},
        {"Arrokuda", {0}},
        {"Barraskewda", {0}},
        {"Toxel", {0}},
        {"Toxtricity", {0,1}},
        {"Sinistea", {0,1}},
        {"Polteageist", {0,1}},
        {"Hatenna", {0}},
        {"Hattrem", {0}},
        {"Hatterene", {0}},
        {"Impidimp", {0}},
        {"Morgrem", {0}},
        {"Grimmsnarl", {0}},
        {"Perrserker", {0}},
        {"Milcery", {0}},
        {"Alcremie", {0,1,2,3,4,5,6,7,8}},
        {"Falinks", {0}},
        {"Pincurchin", {0}},
        {"Snom", {0}},
        {"Frosmoth", {0}},
        {"Stonjourner", {0}},
        {"Eiscue", {0,1}},
        {"Indeedee", {0,1}},
        {"Morpeko", {0,1}},
        {"Cufant", {0}},
        {"Copperajah", {0}},
        {"Duraludon", {0}},
        {"Dreepy", {0}},
        {"Drakloak", {0}},
        {"Dragapult", {0}},
        {"Zacian", {0,1}},
        {"Zamazenta", {0,1}},
        {"Eternatus", {0}},
        {"Kubfu", {0}},
        {"Urshifu", {0,1}},
        {"Zarude", {0,1}},
        {"Regieleki", {0}},
        {"Regidrago", {0}},
        {"Glastrier", {0}},
        {"Spectrier", {0}},
        {"Calyrex", {0,1,2}},
        {"Wyrdeer", {0}},
        {"Kleavor", {0}},
        {"Ursaluna", {0,1}},
        {"Basculegion", {0,1}},
        {"Sneasler", {0}},
        {"Overqwil", {0}},
        {"Enamorus", {0,1}},
        {"Sprigatito", {0}},
        {"Floragato", {0}},
        {"Meowscarada", {0}},
        {"Fuecoco", {0}},
        {"Crocalor", {0}},
        {"Skeledirge", {0}},
        {"Quaxly", {0}},
        {"Quaxwell", {0}},
        {"Quaquaval", {0}},
        {"Lechonk", {0}},
        {"Oinkologne", {0,1}},
        {"Tarountula", {0}},
        {"Spidops", {0}},
        {"Nymble", {0}},
        {"Lokix", {0}},
        {"Pawmi", {0}},
        {"Pawmo", {0}},
        {"Pawmot", {0}},
        {"Tandemaus", {0}},
        {"Maushold", {0,1}},
        {"Fidough", {0}},
        {"Dachsbun", {0}},
        {"Smoliv", {0}},
        {"Dolliv", {0}},
        {"Arboliva", {0}},
        {"Squawkabilly", {0,1,2,3}},
        {"Nacli", {0}},
        {"Naclstack", {0}},
        {"Garganacl", {0}},
        {"Charcadet", {0}},
        {"Armarouge", {0}},
        {"Ceruledge", {0}},
        {"Tadbulb", {0}},
        {"Bellibolt", {0}},
        {"Wattrel", {0}},
        {"Kilowattrel", {0}},
        {"Maschiff", {0}},
        {"Mabosstiff", {0}},
        {"Shroodle", {0}},
        {"Grafaiai", {0}},
        {"Bramblin", {0}},
        {"Brambleghast", {0}},
        {"Toedscool", {0}},
        {"Toedscruel", {0}},
        {"Klawf", {0}},
        {"Capsakid", {0}},
        {"Scovillain", {0}},
        {"Rellor", {0}},
        {"Rabsca", {0}},
        {"Flittle", {0}},
        {"Espathra", {0}},
        {"Tinkatink", {0}},
        {"Tinkatuff", {0}},
        {"Tinkaton", {0}},
        {"Wiglett", {0}},
        {"Wugtrio", {0}},
        {"Bombirdier", {0}},
        {"Finizen", {0}},
        {"Palafin", {0,1}},
        {"Varoom", {0}},
        {"Revavroom", {0}},
        {"Cyclizar", {0}},
        {"Orthworm", {0}},
        {"Glimmet", {0}},
        {"Glimmora", {0}},
        {"Greavard", {0}},
        {"Houndstone", {0}},
        {"Flamigo", {0}},
        {"Cetoddle", {0}},
        {"Cetitan", {0}},
        {"Veluza", {0}},
        {"Dondozo", {0}},
        {"Tatsugiri", {0,1,2}},
        {"Annihilape", {0}},
        {"Clodsire", {0}},
        {"Farigiraf", {0}},
        {"Dudunsparce", {0,1}},
        {"Kingambit", {0}},
        {"Great Tusk", {0}},
        {"Scream Tail", {0}},
        {"Brute Bonnet", {0}},
        {"Flutter Mane", {0}},
        {"Slither Wing", {0}},
        {"Sandy Shocks", {0}},
        {"Iron Treads", {0}},
        {"Iron Bundle", {0}},
        {"Iron Hands", {0}},
        {"Iron Jugulis", {0}},
        {"Iron Moth", {0}},
        {"Iron Thorns", {0}},
        {"Frigibax", {0}},
        {"Arctibax", {0}},
        {"Baxcalibur", {0}},
        {"Gimmighoul", {0,1}},
        {"Gholdengo", {0}},
        {"Wo-Chien", {0}},
        {"Chien-Pao", {0}},
        {"Ting-Lu", {0}},
        {"Chi-Yu", {0}},
        {"Roaring Moon", {0}},
        {"Iron Valiant", {0}},
        {"Koraidon", {0,1,2,3,4}},
        {"Miraidon", {0,1,2,3,4}},
        {"Walking Wake", {0}},
        {"Iron Leaves", {0}},
        {"Dipplin", {0}},
        {"Poltchageist", {0,1}},
        {"Sinistcha", {0,1}},
        {"Okidogi", {0}},
        {"Munkidori", {0}},
        {"Fezandipiti", {0}},
        {"Ogerpon", {0,1,2,3}},
        {"Archaludon", {0}},
        {"Hydrapple", {0}},
        {"Gouging Fire", {0}},
        {"Raging Bolt", {0}},
        {"Iron Boulder", {0}},
        {"Iron Crown", {0}},
        {"Terapagos", {0,1,2}},
        {"Pecharunt", {0}},
        };

    QMap<QString, QMap<QString, int>> currectlySelectedStarters = {
        {"hono", {{"id", 909}, {"form", 0}, {"gender", 0}, {"rare", 0},{"gem", 0}}},
        {"kusa", {{"id", 906}, {"form", 0}, {"gender", 0}, {"rare", 0},{"gem", 0}}},
        {"mizu", {{"id", 912}, {"form", 0}, {"gender", 0}, {"rare", 0},{"gem", 0}}}
    };

    int generateBinary(const std::string& schema, const std::string& jsonFile, const std::string& path, bool debug = false);
    int generateJson(const std::string& schema, const std::string& inputFile, const std::string& path, bool debug = false);
    uint64_t fnv1a_64(const std::string& str, uint64_t basis = 0xCBF29CE484222645);
    void patchScenes(const QList<QPair<QString, QString>>& jsonFile, QList<QString> outputs, QVector<int> devId, QVector<int> formId, QVector<int> gender, QVector<bool> rare);
    void patchScenesOne(const QList<QPair<QString, QString>>& jsonFile, QList<QString> outputs, QVector<int> devId, QVector<int> formId, QVector<int> gender, QVector<bool> rare);

    bool getAllowedPokemon(allowedPokemonLimiter limiter, QMap<int, QList<int>>& allowedList, QString check) override;
    void randomizePokemon(QMap<int, QList<int>>& allowedPokemon, int& devid, int& form, int& gender, bool& rare, int shinyrate, json& changedFile) override;
    void randomizePokemonMoves() override;
    void randomizeTeraType(json& checkFile, bool randomizeTeraType, int devId, int formId);
    std::string getTeraType();
    int getTeraTypeInt(std::string teraType);
    inline void closeFileAndDelete(QString path, QString schema, QString outputFile, json& maps, bool deleteFile=true);

    template <typename T>
    void printSceneTables(T table);
	
private:
    void modifyPokemonScene(QVector<int> devId, QVector<int> formId, QVector<int> gender, QVector<bool> rare, QString input, QString output) override;
    void recursiveFindOfPokemonSceneTable(json& sceneFile, QVector<int> devId, QVector<int> formId, QVector<int> gender, QVector<bool> rare) override;
};

inline void SVShared::closeFileAndDelete(QString path, QString schema, QString outputFile, json& maps, bool deleteFile){
    // Write the modified JSON back to the output file
    QFile outFile(qBaseDir.filePath(path));
    if (!outFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qFatal() << "Error: Could not open output file for writing!";
        return;
    }

    QTextStream outStream(&outFile);
    outStream << QString::fromStdString(maps.dump(2)); // Pretty print JSON
    outFile.close();

    generateBinary(qBaseDir.filePath(schema).toStdString(),
                   qBaseDir.filePath(path).toStdString(),
                   outputFile.toStdString(), true);

    if(deleteFile == true)
        QDir().remove(qBaseDir.filePath(path));
}

template <typename T>
void SVShared::printSceneTables(T table){
    std::string name = pokemonMapping["pokemons_devid"][table->DevId()]["name"];
    QString pokemonName = QString::fromUtf8(name.c_str());
    qDebug() << "  DevId: " << pokemonName;
    qDebug() << "  FormId: " << static_cast<int>(table->FormId());

    QString textForPokemon = "MALE";
    if(femaleOnlyPokemon.contains(pokemonName)){
        textForPokemon = "FEMALE";
    }else if(genderlessPokemon.contains(pokemonName)){
        textForPokemon = "GENDERLESS";
    }else if(genderForms.contains(pokemonName)){
        if(static_cast<int>(table->FormId()) == 1){
            textForPokemon = "FEMALE";
        }
    }else if(formsMaleOnly[pokemonName].contains(table->FormId())){
        textForPokemon = "MALE";
    }else{
        if(static_cast<int>(table->Sex()) == 1){
            textForPokemon = "FEMALE";
        }
    }
    qDebug() << "  Sex: " << textForPokemon;

    QString value = "False";
    if(static_cast<int>(table->Rare())  != 0){
        value = "True";
    }
    qDebug() << "  Rare: " << value;

    if(static_cast<int>(table->Field_04()) != 0){
        value = "True";
    }
    qDebug() << "  IsEgg: " << value;
    qDebug() << "  Scale: "<< static_cast<int>(table->Field_05());
    qDebug() << "  Field06: " << static_cast<int>(table->Field_06());
    qDebug() << "  Field07: " << static_cast<int>(table->Field_07());

    value = "False";
    if(table->Field_08() != false){
        value = "True";
    }
    qDebug() << "  IsVisible: " << value;
}


#endif // SV_SHARED_CLASS_H
